### ISSUE TITLE
Incorrect price of the product is displayed in cart  

### ISSUE THREAD

**Issue by Munish7986** [Munish7986/Laplap-Customer#43]
Incorrect price of the product is displayed in cart  

![screenshot_2018-01-27-14-19-19-511_com lapalap_rider_app 1](https://user-images.githubusercontent.com/19631677/35470764-850798aa-0375-11e8-81a1-1d1e5a3e436e.png)
 
![screenshot_2018-01-27-14-14-54-040_com lapalap_rider_app 1](https://user-images.githubusercontent.com/19631677/35470762-80912750-0375-11e8-9189-c658feb0926e.png)

**Comment by scubesvn** [comment]
Fixed!

**Comment by Munish7986** [comment]
Still persists

![whatsapp image 2018-02-07 at 5 09 37 pm](https://user-images.githubusercontent.com/19631677/35914800-a2e08b30-0c2a-11e8-815c-fdafcda0354f.jpeg)
